# Special the runtime
language: node_js

# Special the node version, can set multi versions
node_js:
  - 10
  - 12
  - 14

# Set the script for running
script:
  - npm test

# Set which branch should fire the CI flow
branches:
  only:
    - master
    - develop
